- src/site/_includes/components/pageheader.njk
I was struggling to properly style for mobile browsers and discovered that the viewport wasn't set. This was making setting width and relative font properties very difficult. Adding the viewport makes it much easier.
> added viewport meta block to pageheader

- .eleventy.js
empty files cause syntax errors, because there is no empty data given after the JSON entry
> fix(jsonify): default to empty string on empty content

- .eleventy.js
- package-lock.json
- package.json
- src/site/_includes/layouts/note.njk
- src/site/index.njk
This approach eliminates `markdown-it-hashtag` and implements its own regex to handle after the HTML gets rendered. It solves the tag vs attribute problem much more easily.
> A custom content taggification

- src/site/_data/filetree.js
- Filetree used to only be sorted on the top level
- Sorting is now case-insensitive because that's how Obsidian does it
> feat(filetree): sort filetree recursively

- src/site/_includes/components/sidebar.njk
- src/site/_includes/layouts/note.njk
- src/site/index.njk
This is a small PR that changes some generic divs to semantic tags to tell the browser and screen reader about what is what. It supposed to be better for accessibility.
> Semantic Tags

- .eleventy.js
- src/site/_includes/layouts/note.njk
- src/site/index.njk
According to [DataView docs](https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/#inline-fields), users should be able to add DataView value with hidden keys with the following format:
```md
This will not show the (longKeyIDontNeedWhenReading:: key).
```
Which will show as the following in the Reader Mode:
```md
This will not show the key.
```
This PR implements just that for the notes published.
> Hide dataview variable

- plugin-info.json
- src/site/_includes/components/linkPreview.njk
- src/site/_includes/components/references.njk
- src/site/_includes/layouts/note.njk
- src/site/styles/digital-garden-base.scss
- src/site/styles/style.scss
This PR implements 2 features:
1. Tooltip get cached by **path without the id**. For example, if the link to 2 sections of the same page like these `/path/#id-1` and `/path/#id-2`, it will cache against `/path/` only. This way, caching is more efficient.
2. For paths with id, it will automatically scroll to that id in the tooltip which is better for referencing.
> Tooltip Enhancements

- .eleventy.js
- src/site/_data/dynamics.js
- src/site/_includes/components/pageheader.njk
- src/site/_includes/layouts/note.njk
- src/site/index.njk
This PR implements a Dynamic import of liquid components in various slots. It handles exceptions gracefully so that the site works if the necessary file structure is missing. This is a step toward better maintainability and merging from upstream.
These are the namespaces currently supported:
1. common
2. index
3. notes
These are the supported slots:
1. header
2. afterContent
3. footer
The files should be placed using the following format:
```
src/site/_includes/components/user/<namespace>/<slot>/<filename>.njk
```
For example to add common content in every pages header right after the title and tags the file should be placed in the following directory:
```
src/site/_includes/components/user/common/header/
```
Or,
Say, you have a comment system implemented in a file (e.g. `comment.njk`) …
> Dynamic import implementation

- src/site/_includes/components/graphScript.njk
- src/site/_includes/components/sidebar.njk
- src/site/styles/digital-garden-base.scss
This PR implements some hover style changes. Due to this, whenever hovered on a node, that node and immediate neighbours and links will be shown in an accent colour and all other nodes and links will be muted.
Also, the global graph button icon has been changed from the fullscreen button to the globe button.
The new fullscreen button opens the local graph in full screen. This is particularly helpful since we have depth slider now.
> Graph Enhancements

- src/site/_includes/components/graphScript.njk
- src/site/styles/digital-garden-base.scss
- src/site/styles/style.scss
It adds to CSS vars so that the graph colours can be tweaked. Some themes' accents and muted colours are too close to make any noticeable differences.
> CSS vars to control graph colors

- src/site/_includes/components/calloutScript.njk
**Previously**:
When there are nested collapsible callouts, if you want to open a child one, by clicking on it, the parent one will close. You would have to re-open the parent callout to see the now-open child one.
**Now**:
To open and close a collapsible callout, you have to click on the "callout-title" div; resolve the problem with nested one.
[Live Preview](https://voidblueprint.vercel.app/void-blueprint/physics/classic-physics/electro-magnetism/charge-conservation-law/)
> Resolve collapsible nested callouts

- .eleventy.js
Really small change to makes it easier to apply custom styles to specific tags with CSS.
As an example:
In Obsidian I use a small snipet to add color to some bits of text:
- **Editing**: ![image](https://user-images.githubusercontent.com/76615801/220070181-5bdbb1e8-3c76-4f55-a304-e05a982ec275.png)
- **Reading**: ![image](https://user-images.githubusercontent.com/76615801/220070259-8cdd1b5a-c918-40c8-99ad-5dd9da81f853.png)
I achive this using this css code:
```css
a[href^="#h-"]{
display:none !important;  
}
a[href^="#h-a"] + em {
color: rgb(0,255,255);
}
```
To make it also work here, all I need to do is add the small change I've made + this code in _customstyle.css_:
```css
a.tag[data-content^="#h"]{
display: none !important;
}
a.tag[data-content^="#h-a"] + em {
color: rgb(0,255,255) …
```
> Add new attribute to tags

- .eleventy.js
Another step towards hackability. Users can add js in `src/site/scripts` to serve from the garden instead of CDN or remote sources.
> feat: Allow users to put scripts in src/site/scripts folder

- .eleventy.js
- plugin-info.json
- src/helpers/userSetup.js
Another step towards hackability. This PR adds a `userSetup.js` in the `helpers` so that use can configure the markdown processor and eleventy further in a merge-safe way.
> feat: User setup

- plugin-info.json
**Merge this if it makes sense to you.**
Currently, `vercel.json` is in the `filesToModify` in the `plugin-info.json`. Any settings the users can put will be overridden in every update.
On the other hand, this file doesn't get modified often from the template's perspective. But users can add additional things. Like I make the GitHub silent.
Adding this to `filesToAdd` may allow users to have smoother updating experience.
> Move vercel.json to filesToAdd

- .eleventy.js
- src/site/styles/digital-garden-base.scss
In some themes (at least in the Minimal theme and/or in all themes), markdown tables are not scrollable horizontally in mobiles.
That can be fixed by an `overflow-y: auto` on the `cm-s-obsidian` class but that breaks the styling. I've googled it a bit and found that in such situations tables should be wrapped in another container, and that container should have `overflow-y: auto`.
It is true that our current setup allows us to implement this without touching the core template, but I thought it was a problem most will face now or then and we can ship the solution with the template.
> Table wrapper for markdown tables

- src/site/_includes/components/graphScript.njk
- src/site/_includes/components/sidebar.njk
This is a housekeeping PR which ports the current Graph to AlpineJS.
The rationale behind this is:
1. We're already using AlpineJS, so no extra libraries.
2. Eventually if we extend the graph functionality more (e.g. missing links, tags, etc.) AlpineJS version will be easier to maintain.
> Port the graph to alpineJS

- src/site/_includes/components/pageheader.njk
- src/site/_includes/components/timestamps.njk
Because cdn.jsdelivr.net cannot be accessed in China, it has been replaced with fastly.jsdelivr.net.
> Change cdn.jsdelivr.net to fastly.jsdelivr.net.

- .eleventy.js
The admonition plugin accepts parameters on the first 4 lines. These lines are displayed in the resulting html and the collapsing does not work.
For example in the following block : 
```
ad-quote
title: Summary
icon: dice-five
collapse: open
content here
```
The rendered html shows the title, icon and collapse strings, and collapsing is broken.
See below :
The fix I propose tries to integrate the title, the collapsible state.
Unfortunately custom icon names and custom color are trickier to convert.
Below are some sample tests i made : 
PS : I'll try to do some research and see if converting the admonition blocks directly in the obsidian plugin using the rendering functions of the admonition plugin might be better.
> fix display bug for admonition to callout conversion

- .eleventy.js
If you have a dataview query in a note that does not return any results, the current dataview styling throws an error as it tries to access `.classList` of null
> Add null checks for empty dataview queries

- .eleventy.js
- package-lock.json
- package.json
- src/site/_includes/components/pageheader.njk
Closing #148 in favour of this : I needed to keep the branch seperate so i can continue working on other things.
Old comment
This has been bothering me for some time in this otherwise awesome project this one npm plugin was generating audit findings.
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see …
```
> removing vulnerable favicon generator and replacing it with alternative

- src/site/styles/obsidian-base.scss
This PR tweaks the callout color for question/help/faq type to match the obsidian standard yellow.
> fix: 💄 question/help/faq callout color to match obsidian

- src/site/404.njk
- src/site/_data/meta.js
- src/site/_includes/layouts/index.njk
- src/site/_includes/layouts/note.njk
Must be seen in connection with https://github.com/oleeskild/obsidian-digital-garden/pull/473 and https://github.com/oleeskild/obsidian-digital-garden/issues/472
This commit uses the SITE_MAIN_LANGUAGE set in the .env for all lang attributes in html elements. If no SITE_MAIN_LANGUAGE is set, it defaults to `<html lang="en">`.
This is part of my first pull request (and I have zero Obsidian plugin development experience), so please be very critical of my work.
> Adds user selected language in <html lang="">

- package-lock.json
**Fixes 2 CVEs found in semver**
Bumps [semver](https://github.com/npm/node-semver) from 5.7.1 to 5.7.2.
- [Release notes](https://github.com/npm/node-semver/releases)
- [Changelog](https://github.com/npm/node-semver/blob/v5.7.2/CHANGELOG.md)
- [Commits](https://github.com/npm/node-semver/compare/v5.7.1...v5.7.2)
---
updated-dependencies:
- dependency-name: semver dependency-type: indirect ...
> Security fix: Bump semver from 5.7.1 to 5.7.2

- .eleventy.js
- src/site/_includes/components/timestamps.njk
- src/site/sitemap.njk
Fixes issue #206 
1. Updated `dateToZulu` filter to return `""` whenever the string is invalid 
2. added fallback timestamp parsing functions from luxon when the default method `fromISO()` raises an error
3. Update sitemap to also use `dateToZulu` filter
> Fix Timestamp Parsing Error that renders Invalid Datetime

- .eleventy.js
`package.json` command `cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy` doesn't minify HTML because the config file only checks for `NODE_ENV`.
Also turned on `conservativeCollapse` and `preserveLineBreaks`, which will collapse whitespace to just 1 space or 1 newline instead of removing it entirely. This fixes an issue where mathjax blocks would not have spaces between text.
> Check for ELEVENTY_ENV for minifier

- src/helpers/filetreeUtils.js
I have noticed that since strings are compared using alphabetical order, if they start with a number they won't be compared correctly. For example, '10' will be placed before '2' in the sorted results. So, I tried to fix this problem using a regular expression that extracts the numeric portion at the beginning of each string (if it's possible) and performs a numerical comparison.
See an example below.
> Fix sorting order for numeric strings

- .eleventy.js
Fixes #266 
A not-very-elegant solution to avoid rendering the `callout-content` div when the callout only has a title, like this:
```
> [!info] this callout has no title
```
Not sure how to make it better, just wanted to fix this papercut.
Happy to make improvements if given feedback :slightly_smiling_face:
> Dont render callout-content div if blank

- .github/dependabot.yml
From: https://www.11ty.dev/docs/plugins/rss/#installation v2 of this this plugin requires Eleventy v3.0 or newer. v1 of this plugin is compatible with Eleventy 0.11 or newer.
This change tells dependabot not to go over v1.2.0
> Update to ignore a version of eleventy-plugin-rss that is too new.

- .github/dependabot.yml
There's a yaml typo in the `dependabot.yml` file (missing `:` after `versions`)
Should be:
```yaml
versions: [ "^1.2.0" ]
```
Error that happened in my repo:
> fix: add missing `:` (yaml typo)
