oleeskild/digitalgarden

.eleventy.js, package-lock.json, package.json, src/helpers/linkUtils.js, src/site/index.11tydata.js, src/site/notes/notes.11tydata.js, src/site/styles/digital-garden-base.scss
This PR complements https://github.com/oleeskild/obsidian-digital-garden/pull/141
=> Support for block ID

src/helpers/linkUtils.js, src/site/_data/filetree.js, src/site/_includes/layouts/note.njk, src/site/index.11tydata.js, src/site/lunr.njk
=> Title support throughout the garden

src/site/_includes/components/pageheader.njk
=> Support for metatags

netlify/functions/search/search.js, src/site/_includes/components/searchScript.njk, src/site/_includes/layouts/note.njk, src/site/lunr-index.js, src/site/lunr.njk, src/site/styles/style.scss
=> Tag support in UI and Search

.eleventy.js, netlify/functions/search/search.js, src/site/lunr.njk
This PR implements a tag search targeted to tags of the content instead of a general search.
=> Targeted Tag Search

package-lock.json, package.json, src/site/_data/meta.js, src/site/get-theme.js
=> Download and link theme

src/site/styles/obsidian-base.scss, src/site/styles/style.scss
This PR contains a small fix to show the quote icon in the quote callouts.
=> Quote callout fix

src/site/_data/dynamics.js, src/site/_includes/components/filetreeNavbar.njk, src/site/_includes/components/sidebar.njk, src/site/_includes/layouts/note.njk, src/site/index.njk
This PR implements 2 more placeholders for dynamics components for the notes and index.
Additionally, for file tree, and sidebar: 2 for each.
Fixes #66
=> More slots for dynamic components

.eleventy.js, package-lock.json, package.json, src/site/_includes/layouts/note.njk, src/site/index.njk
Fixes https://github.com/oleeskild/digitalgarden/issues/55
=> fix: Inline code wrong highlight detection

.eleventy.js, package-lock.json, package.json, src/site/styles/digital-garden-base.scss
Fixes https://github.com/oleeskild/obsidian-digital-garden/issues/169
=> fix: Nested TOC

.eleventy.js
Fixes: https://github.com/oleeskild/obsidian-digital-garden/issues/204
=> fix: Footnote in heading

.eleventy.js, package-lock.json, package.json, src/site/get-theme.js
This PR implements the following things:
1. Minify all HTML files.
2. Minify CSS compiled from SCSS.
3. Removes all the comments except the first (generally the credit) from the downloaded theme. This cuts down the size significantly.
Implements #92
=> feat: Minification

.eleventy.js, package-lock.json, package.json
Actually, our header slug generation system conflicted with the footnote plugin. Now, I'm generating the ids via a plugin with our signification function from the utils.
=> Footnote fix via a better way

src/site/404.njk, src/site/_includes/components/pageheader.njk, src/site/styles/digital-garden-base.scss, src/site/styles/obsidian-base.scss, src/site/styles/style.scss
This is an alternate approach for #82 
Here I used default font-stack like bootstrap.
=> Removed all google fonts

src/site/_includes/components/calloutScript.njk, src/site/_includes/components/filetree.njk, src/site/_includes/components/filetreeNavbar.njk, src/site/_includes/components/graphScript.njk, src/site/_includes/components/lucideIcons.njk, src/site/_includes/components/pageheader.njk, src/site/_includes/components/searchButton.njk, src/site/_includes/components/searchContainer.njk, src/site/_includes/components/sidebar.njk, src/site/_includes/layouts/index.njk, src/site/_includes/layouts/note.njk, src/site/styles/digital-garden-base.scss
Implements #97
Merge it only if it seems like a good decision.
=> Migrate to lucide from fontawesome

src/site/_data/meta.js, src/site/_includes/components/timestamps.njk, src/site/_includes/layouts/note.njk, src/site/styles/digital-garden-base.scss
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/200
It renders the timestamps based on settings with luxon.
An interesting thing is, this implementation will convert any element with `human-date` class. Users can add arbitrary timestamps in their notes and it will work too.
=> feat: Timestamp support

src/site/_includes/components/filetree.njk, src/site/_includes/components/searchButton.njk, src/site/_includes/components/searchContainer.njk, src/site/styles/digital-garden-base.scss
I noticed that the icon positioning is a little off in the file tree and search. Fixed them in this PR
=> Fixed lucide icon alignments

src/site/_data/filetree.js, src/site/_includes/components/filetree.njk
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/228
=> Support for hide in filetree

src/helpers/linkUtils.js, src/site/_data/meta.js, src/site/_includes/components/sidebar.njk, src/site/styles/digital-garden-base.scss
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/221
=> note icon on backlinks

src/site/_data/filetree.js
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/244
=> Pinned note in filetree

src/helpers/linkUtils.js, src/site/_includes/components/graphScript.njk
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/245
=> Hide in graph

src/helpers/linkUtils.js
Fix for an overlooked change which was not needed in graph generation
=> Graph fix after dg-path feature

.eleventy.js, .gitignore, package-lock.json, package.json
This PR replaces `img` with `picture` tags with `srcset` for all 3 breakpoints and fallback to the default image.
Should make sites more responsive and users can upload images without worrying about sizes.
=> Image optimization

.eleventy.js, src/site/_includes/layouts/index.njk, src/site/_includes/layouts/note.njk
Complements: https://github.com/oleeskild/obsidian-digital-garden/pull/276
=> Transform dataview tables to add proper classes

src/site/styles/custom-style.scss
=> Fix typo in custom-syle.css

package-lock.json, src/site/_includes/components/calloutScript.njk, src/site/_includes/components/pageheader.njk
* Remove polyfill.io link #275 
* Improve performance by making scripts async [#311](https://github.com/oleeskild/obsidian-digital-garden/issues/311)
* Update package dependencies
=> Remove polyfill.io and make all js files async
